### ISSUE TITLE
Materials white when in MH in "Pose / Animate -> Skeleton" Tab

### ISSUE THREAD

**Issue by Palmer-JC** [makehumancommunity/makehuman-plugin-for-blender#55] opened 2019-06-27 16:23 UTC
I am now working almost full time on finishing Kinect.  I was experimenting with getting different meshes.  One time, I had left the MakeHuman session on the Skeleton selection area.  When you do this the materials are just brand new principled nodes, basically all white with not textures.

**Comment by joepal1976** [comment] 2019-06-28 07:40
Yeah. The socket call reads what material is currently set on G.app.selectedHuman. In pose/skeleton/some  other views, a different (usually transparent) material is set.

It probably should read materials from some other place, although I currently don't know exactly where.

**Comment by Aranuvir** [comment] 2019-06-29 10:54
skeletonlibrary.py changes the material in its onShow and onHide functions and stores that information locally. Technically it should be possible to read out the local information without the need of altering MakeHuman itself, though this will be probably quite cumbersome. 
IMHO the cleanest solution to overcome the problem is to introduce a new property in human.py (self.backupMaterial) set to None and alter the onShow/onHide functions accordingly. Then you can run a simple "if human.material.name == 'XrayMaterial' and human.backupMaterial: ..."

**Comment by Aranuvir** [comment] 2019-06-30 10:35
... um, I forgot to mention, it has to be done for each proxy, too. Not so convenient, either.

**Comment by marbel9** [comment] 2020-06-17 22:36
I'm having the same issue with the material preview and rendered view ports. Does this stem from the same problem?

**Comment by joepal1976** [comment] 2020-06-18 06:43
Unless you imported using MPFB while MH was in pose mode, it's unlikely it's the same problem.

**Comment by Hunanbean** [comment] 2020-08-07 08:23
As is probably known, but to clarify further. even if after you import from the 'pose/animate' tab and the materials fail, if you then delete all in blender, put makehuman to the modeling or other proper importable page, when you reimport, the materials stay failed as they did when you initially imported from 'pose/animate' tab.
Possible relation to issue #79 at its core? I would have no way of verifying that assumption.

**Comment by Aranuvir** [comment] 2020-12-01 01:35
Providing a fix for this issue, though it was a problem on the MakeHuman side of the socket. To test the fix both MakeHuman and the socket plugin need an update.

**Comment by joepal1976** [comment] 2020-12-05 14:17
Tested and working for me

**Closed by joepal1976** 2020-12-05 14:17 UTC
Labels: fix exists ...
