### ISSUE TITLE
Size problem when syncing pose

### ISSUE THREAD

**Issue by tomasruizr** [makehumancommunity/makehuman-plugin-for-blender#11] opened 2016-09-03 11:03 UTC
Hi,

When I export the mhx2 file to be in meters, or change the size of the mh character in Blender,  if i want to sync the pose it does not match the sizes of the bones.

Thanks for your help, and sorry if is an obvious mistake.

TR
Export Settings:
![export settings](https://cloud.githubusercontent.com/assets/4132575/18224467/ac7beb0e-71ac-11e6-917f-bc9f0cfa7812.png)
the way is imported into blender:
![the way is imported into blender](https://cloud.githubusercontent.com/assets/4132575/18224466/ac7ab9fa-71ac-11e6-81b4-1e4d83fe4420.png)
what happens when i hit sync pose:
![what happens when i hit sync](https://cloud.githubusercontent.com/assets/4132575/18224468/ac904338-71ac-11e6-8f1d-b476cfa34df1.png)

**Comment by Palmer-JC** [comment] 2018-10-18 14:12
Ah, yes the problem is you must check "No Location Translation" when not in decimeters.  For poses this probably not a problem.  Expressions sort of  loose something though.

I tried adjusting the data on the Blender side by first [detecting the units](https://github.com/makehumancommunity/makehuman-plugin-for-blender/blob/master/blender_source/MH_Community/rig_info.py#L53), but failed.

The current version, now [requires this be checked](https://github.com/makehumancommunity/makehuman-plugin-for-blender/blob/master/blender_source/MH_Community/__init__.py#L179) in this case, so it at least cannot happen anymore.  On this basis, closing this.

**Closed by Palmer-JC** 2018-10-18 14:12 UTC
