### ISSUE TITLE
I can not import mhx2 format error Blender 2.83

### ISSUE THREAD

**Issue by Moecon** [makehumancommunity/makehuman-plugin-for-blender#75] opened 2020-06-13 19:47 UTC
i'm use windows 10 
![error](https://user-images.githubusercontent.com/66885278/84577758-2884b080-ad8d-11ea-8009-856d3b4f2ed2.png)
![error 2](https://user-images.githubusercontent.com/66885278/84577780-579b2200-ad8d-11ea-956d-51a02ed0cfe8.png)

**Comment by Aranuvir** [comment] 2020-06-14 12:09
You cannot import MHX2 with this plugin. Please read the docs. 
Your error is coming from your system indicating that it cannot connect to MakeHuman, that's a problem you have to fix on your machine...
Not a bug, closing...

**Closed by Aranuvir** 2020-06-14 12:09 UTC
